# Generated by Django 3.2.5 on 2021-07-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
