# Generated by Django 3.2.5 on 2021-07-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('treated', 'treated'), ('not treated yet', 'not treated yet')], max_length=50, null=True),
        ),
    ]
