# Generated by Django 3.2.5 on 2021-07-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, null=True)),
                ('p_mail', models.EmailField(max_length=254)),
                ('p_phone', models.PositiveBigIntegerField(null=True)),
                ('p_web', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
