# Generated by Django 3.2.5 on 2021-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='p_ados',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
