# Generated by Django 3.2.5 on 2021-07-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_provider_p_ados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='p_phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
